name: Deploy Infrastructure & Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 4. Initialize Terraform
      - name: Terraform Init
        working-directory: infra
        run: terraform init -reconfigure

      # 5. Select or create workspace
      - name: Terraform Workspace
        working-directory: infra
        run: |
          TERRAFORM_WORKSPACE=${{ github.event.inputs.environment }}
          terraform workspace list
          terraform workspace select $TERRAFORM_WORKSPACE || terraform workspace new $TERRAFORM_WORKSPACE

      # 6. Terraform Plan
      - name: Terraform Plan
        working-directory: infra
        run: |
          TERRAFORM_WORKSPACE=${{ github.event.inputs.environment }}
          terraform plan -var-file="${TERRAFORM_WORKSPACE}.auto.tfvars"

      # 7. Terraform Apply
      - name: Terraform Apply
        working-directory: infra
        run: |
          TERRAFORM_WORKSPACE=${{ github.event.inputs.environment }}
          terraform apply -auto-approve -var-file="${TERRAFORM_WORKSPACE}.auto.tfvars"

      # 8. Configure kubectl
      - name: Configure kubectl
        working-directory: infra
        run: |
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ap-southeast-2

      # 9. Apply Kubernetes manifests
      - name: Deploy K8s Manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml

      # 10. Apply Fluentd logging
      - name: Deploy Fluentd Logging
        run: |
          kubectl apply -f logging/fluentd/namespace.yaml
          kubectl apply -f logging/fluentd/fluentd-configmap.yaml
          kubectl apply -f logging/fluentd/fluentd-rbac.yaml
          kubectl apply -f logging/fluentd/fluentd-daemonset.yaml
